Repository Dev-FE-1/idle-intranet-service, pull requests merged in 2024-07, with the labels that each got.

#75 [Feat] 동적 라우팅 기능 추가
  src/components/NavBar/Menu.js
  src/pages/Members/Members.js
  src/pages/Profile/Profile.js
  src/pages/WorkManage/WorkManage.js
  src/routes/Route.js
  src/utils/constants.js
  src/utils/matchRoute.js
Labels: ✨ Feature

#76 [Fix/Refactor]ESLint, 스타일링 관련 코드 정리 및 기능 개선 작업
  .eslintrc.cjs
  src/App.js
  src/components/Button/Button.js
  src/components/Icon/Icon.js
  src/components/Input/Input.js
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
  src/components/NavBar/Menu.js
  src/components/NavBar/NavBar.css
  src/components/Pagination/Pagination.js
  src/components/PersonalInfo/PersonalDetails.css
  src/components/PersonalInfo/PersonalDetails.js
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/ProfileInfo.js
  src/components/PersonalInfo/WorkInfo.js
  src/components/SignInForm/SignInForm.js
  src/pages/404/PageNotFound.js
  src/pages/Home/Home.js
  src/pages/Members/Members.js
  src/pages/Profile/Profile.js
  src/pages/WorkManage/WorkManage.js
  src/pages/index.js
  src/routes/Route.js
  src/utils/icons.js
  src/utils/matchRoute.js
Labels: 🐞 BugFix, 🔨 Refactor

#88 [Fix/Feat] 멤버 및 휴가 데이터베이스 스키마 개선
  server/data/vacationRequests.json
  server/database.js
Labels: ✨ Feature, 🐞 BugFix

#89 [Feat] API GET 요청 기능 추가
  .gitignore
  package-lock.json
  package.json
  server/index.js
  src/fetchData.js
Labels: 📬 API

#90 [Feature] 로그인 기능 구현, API client 생성 및 토큰을 통한 사용자 유효성 검사
  .env
  .eslintrc.cjs
  package-lock.json
  package.json
  server/data/members.json
  server/index.js
  server/passwords.js
  src/components/Auth/ApiClient.js
  src/components/Auth/AuthService.js
  src/components/Button/Button.css
  src/components/Button/Button.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/SignInForm/SignInForm.css
  src/components/SignInForm/SignInForm.js
  src/pages/Profile/Profile.css
  src/pages/Profile/Profile.js
  src/pages/SignIn/SignIn.js
  src/routes/Route.js
Labels: 📬 API, 💻 Backend

#92 [Feat] 프로필 페이지에 현재 시각 표시
  package-lock.json
  package.json
  src/components/PersonalInfo/PersonalInfo.js
  src/pages/Profile/Profile.js
  src/routes/Route.js
Labels: ✨ Feature

#91 Feat/main page publishing 45
  src/pages/Home/Home.css
  src/pages/Home/Home.js
  src/utils/icons.js
Labels: 🎨 Html&css

#98 [Design] 홈페이지 스타일링 수정
  package-lock.json
  src/pages/Home/Home.css
  src/pages/Home/Home.js
  src/pages/Profile/Profile.js
Labels: 🎨 Html&css

#101 [Feat] Select 컴포넌트 추가 및 env 파일 삭제
  .env
  src/components/Select/Select.css
  src/components/Select/Select.js
Labels: ✨ Feature

#108 [Feat] 404 페이지 수정
  public/images/404.png
  src/pages/404/PageNotFound.css
  src/pages/404/PageNotFound.js
Labels: 🎨 Html&css

#107 [Feat] 공통 상태를 관리할 Store 컴포넌트 추가 및 사용 예시(프로필 페이지)
  server/index.js
  src/components/Container.js
  src/components/Main.js
  src/components/PersonalInfo/PersonalDetails.js
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/ProfileInfo.js
  src/components/Store.js
  src/pages/404/PageNotFound.js
  src/pages/Home/Home.js
  src/pages/Members/Members.js
  src/pages/Profile/Profile.js
  src/pages/SignIn/SignIn.js
  src/pages/WorkManage/WorkManage.js
  src/utils/sortByPeriod.js
Labels: ✨ Feature

#109 [Feature] 토큰 유효성 검사
  server/index.js
  src/components/API/ApiClient.js
  src/components/API/AuthService.js
  src/components/API/MemberService.js
  src/components/Header/Header.js
  src/components/SignInForm/SignInForm.js
  src/pages/Members/Members.js
  src/pages/Profile/Profile.js
  src/routes/Route.js
Labels: ✨ Feature, 📬 API

#114 [Deploy] github pages 배포
  .gitignore
  404.html
  index.html
  package-lock.json
  package.json
  src/components/API/AuthService.js
  src/components/API/MemberService.js
  src/fetchData.js
  src/pages/404/PageNotFound.js
  src/utils/constants.js
  vite.config.js
Labels: 🌏 Deploy

#111 [Bug] 404 페이지 홈으로 이동 버튼 오류 수정
  src/App.js
  src/components/Header/Header.js
  src/components/Layout.js
  src/components/NavBar/Menu.js
  src/components/NavBar/NavBar.js
  src/components/SignInForm/SignInForm.css
  src/components/SignInForm/SignInForm.js
  src/components/Store.js
  src/pages/404/PageNotFound.css
  src/routes/Route.js
Labels: 🐞 BugFix

#116 [Feat] 프로필 페이지의 더미 데이터를 실제 데이터로 변경
  server/index.js
  server/middlewares/authMiddleware.js
  src/api/apiClient.js
  src/api/config.js
  src/api/endpoints/user.js
  src/api/errorHandling.js
  src/components/Avatar/Avatar.css
  src/components/Button/Button.css
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/PersonalInfo/CurrentTime.js
  src/components/PersonalInfo/PersonalDetails.js
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/ProfileInfo.js
  src/components/PersonalInfo/WorkInfo.js
  src/components/Store.js
  src/pages/Profile/Profile.js
  src/utils/userWork.js
Labels: ✨ Feature

#117 [feat] 홈페이지 주요사항을 실제데이터로 변경
  src/pages/Home/Home.css
  src/pages/Home/Home.js
Labels: ✨ Feature

#123 [Feature] 멤버 페이지 검색 기능 구현
  server/index.js
  src/components/API/MemberService.js
  src/components/Pagination/Pagination.js
  src/pages/Members/Members.css
  src/pages/Members/Members.js
Labels: ✨ Feature

#124 [Refactor] 홈페이지 리팩토링
  src/api/endpoints/announcement.js
  src/api/endpoints/member.js
  src/components/Announcements/GalleryItem.js
  src/components/Announcements/TextItem.js
  src/pages/Home/Home.css
  src/pages/Home/Home.js
  src/utils/constants.js
Labels: 🔨 Refactor

#126 [Bug] 404, ESLint, console 에러 해결
  src/App.js
  src/components/Header/Header.js
  src/components/Layout.js
  src/components/Store.js
  src/pages/404/PageNotFound.css
  src/pages/404/PageNotFound.js
  src/routes/Route.js
Labels: 🐞 BugFix

#128 [Feat, Bug, Refactor] 검색기능, Home페이지 추가, 상태관리, 404에러 개선, eslint 에러 해결
  .gitignore
  404.html
  index.html
  package-lock.json
  package.json
  server/index.js
  server/middlewares/authMiddleware.js
  src/App.js
  src/api/apiClient.js
  src/api/config.js
  src/api/endpoints/announcement.js
  src/api/endpoints/member.js
  src/api/endpoints/user.js
  src/api/errorHandling.js
  src/components/API/AuthService.js
  src/components/API/MemberService.js
  src/components/Announcements/GalleryItem.js
  src/components/Announcements/TextItem.js
  src/components/Avatar/Avatar.css
  src/components/Button/Button.css
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Layout.js
  src/components/NavBar/Menu.js
  src/components/NavBar/NavBar.js
  src/components/Pagination/Pagination.js
  src/components/PersonalInfo/CurrentTime.js
  src/components/PersonalInfo/PersonalDetails.js
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/ProfileInfo.js
  src/components/PersonalInfo/WorkInfo.js
  src/components/SignInForm/SignInForm.css
  src/components/SignInForm/SignInForm.js
  src/components/Store.js
  src/fetchData.js
  src/pages/404/PageNotFound.css
  src/pages/404/PageNotFound.js
  src/pages/Home/Home.css
  src/pages/Home/Home.js
  src/pages/Members/Members.css
  src/pages/Members/Members.js
  src/pages/Profile/Profile.js
  src/routes/Route.js
  src/utils/constants.js
  src/utils/userWork.js
  vite.config.js
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#129 [Refactor] ProfileInfo와 PersonalDetails 컴포넌트 재사용성 향상
  src/components/Header/Header.js
  src/components/PersonalInfo/PersonalDetails.js
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/ProfileInfo.js
  src/components/Store.js
  src/pages/Home/Home.js
  src/pages/Profile/Profile.js
Labels: 🔨 Refactor

#132 [Feat] 프로필 정보 수정 기능
  package-lock.json
  package.json
  server/cloudinary.js
  server/index.js
  src/api/config.js
  src/api/endpoints/user.js
  src/components/Avatar/Avatar.css
  src/components/Button/IconButton.css
  src/components/Button/IconButton.js
  src/components/Input/Input.js
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
  src/components/PersonalInfo/EditProfileButton.js
  src/components/PersonalInfo/EditProfileForm.css
  src/components/PersonalInfo/EditProfileForm.js
  src/components/PersonalInfo/ProfileInfo.css
  src/components/PersonalInfo/ProfileInfo.js
  src/pages/Home/Home.css
  src/utils/icons.js
  src/utils/profileImage.js
Labels: ✨ Feature

#134 [Feat/Bug] 공지사항 갤러리 상세 페이지 템플릿 추가 및 순환 참조 오류 해결
  src/api/endpoints/announcement.js
  src/components/Announcements/GalleryItem.js
  src/components/Table/Table.css
  src/pages/Announcement/Announcement.css
  src/pages/Announcement/Announcement.js
  src/pages/Members/Members.css
  src/pages/Members/Members.js
  src/routes/Route.js
  src/utils/constants.js
Labels: ✨ Feature, 🐞 BugFix

#136 [Design]: 디자인 수정
  public/images/announcements_01.png
  public/images/announcements_02.png
  public/images/announcements_03.png
  public/images/announcements_04.png
  public/images/announcements_05.png
  public/images/no-result.png
  server/data/announcements.json
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/pages/Members/Members.css
  src/pages/Members/Members.js
  src/utils/icons.js
Labels: 🎨 Html&css

#137 [Feature] 근무 토글 버튼 기능 구현
  server/index.js
  src/components/API/AttendanceService.js
  src/components/Modal/Modal.js
  src/components/PersonalInfo/EditProfileButton.js
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/WorkInfo.js
  src/components/Store.js
  src/pages/Home/Home.js
  src/pages/Profile/Profile.js
  src/utils/userWork.js
Labels: ✨ Feature

#144 [feat] 공지사항 수정 작업 (#133)
  src/pages/Announcement/Announcement.css
  src/pages/Announcement/Announcement.js
Labels: ✨ Feature

#146 [Setting] 수정된 JSON 데이터 세팅
  server/data/announcements.json
  server/data/attendance.json
  server/data/vacationRequests.json
Labels: ⚙ Setting

#148 [Design] 공지사항 상세 페이지 디자인 수정
  src/pages/Announcement/Announcement.css
  src/pages/Announcement/Announcement.js
Labels: 🎨 Html&css

#150 [Feat]휴가/근무 퍼블리싱, api 적용
  server/database.js
  src/api/endpoints/attendance.js
  src/api/endpoints/vacationRequests.js
  src/components/WorkManagement/VacationTab/VacationCard.css
  src/components/WorkManagement/VacationTab/VacationCard.js
  src/components/WorkManagement/VacationTab/VacationCards.css
  src/components/WorkManagement/VacationTab/VacationCards.js
  src/components/WorkManagement/VacationTab/VacationHistories.css
  src/components/WorkManagement/VacationTab/VacationHistories.js
  src/components/WorkManagement/VacationTab/VacationHistory.css
  src/components/WorkManagement/VacationTab/VacationHistory.js
  src/components/WorkManagement/WorkingTab.css
  src/components/WorkManagement/WorkingTab.js
  src/index.css
  src/pages/WorkManage/WorkManage.css
  src/pages/WorkManage/WorkManage.js
  src/utils/userWork.js
  src/utils/vacation.js
Labels: ✨ Feature

#152 [Feat, Chore] 첫진입시 근무화면 페이지 진입, 기타 휴가 띄어쓰기
  src/pages/WorkManage/WorkManage.js
  src/utils/vacation.js
Labels: ✨ Feature

#157 [Design] 근무/휴가 페이지 UI 스타일 수정
  src/components/Select/Select.css
  src/components/WorkManagement/VacationTab/VacationCard.css
  src/components/WorkManagement/VacationTab/VacationCards.css
  src/components/WorkManagement/VacationTab/VacationHistories.css
  src/pages/WorkManage/WorkManage.css
Labels: 🎨 Html&css

#130 feat: readme.md 작성(#122)
  README.md
  employee-management.db-journal
Labels: ✨ Feature

#161 [Docs] README 파일 수정
  README.md
  employee-management.db-journal
Labels: 📃 Docs

#178 [Fix] cors origin 추가
  server/index.js
Labels: 🐞 BugFix

#179 [Docs] 리드미 수정
  README.md
Labels: 📃 Docs

#182 [Feat] 리드미 오타수정
  README.md
Labels: 🎨 Html&css

#181 [Refactor] 피드백 반영
  package-lock.json
  package.json
  server/checkData.js
  src/components/Avatar/Avatar.js
  src/components/Button/Button.js
  src/components/Input/Input.js
  src/components/Modal/Modal.js
  src/components/PersonalInfo/EditProfileButton.js
  src/components/PersonalInfo/EditProfileForm.css
  src/components/PersonalInfo/EditProfileForm.js
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/WorkInfo.js
  src/components/ProgressRing.js/ProgressRing.js
  src/components/Title/Title.js
  src/fetchData.js
  src/utils/regexp.js
Labels: 🔨 Refactor

#183 [Feat] 캘린더, 휴가 신청 폼, 휴가 카드 컴포넌트에 휴가/반차 신청 기능 및 폼 유효성 체크 추가
  src/api/endpoints/vacationRequests.js
  src/components/Calendar/Calendar.css
  src/components/Calendar/Calendar.js
  src/components/Input/Input.js
  src/components/Select/Select.css
  src/components/VacationForm/VacationForm.css
  src/components/VacationForm/VacationForm.js
  src/components/WorkManagement/VacationTab/VacationCards.css
  src/components/WorkManagement/VacationTab/VacationCards.js
  src/components/WorkManagement/VacationTab/VacationHistories.css
  src/components/WorkManagement/VacationTab/VacationHistories.js
  src/utils/formValidationUtils.js
  src/utils/userVacation.js
  src/utils/vacation.js
Labels: ✨ Feature
