Repository Dev-FE-1/idle-intranet-service, pull requests merged in 2024-06, with the labels that each got.

#11 [settings]eslint 설치 및 설정
  .eslintrc.cjs
  package-lock.json
  package.json
Labels: ⚙ Setting

#10 [settings] prettier 설치 및 설정
  .prettierrc.js
  package-lock.json
  package.json
Labels: ⚙ Setting

#13 fix: 이슈, PR과 프로젝트를 연결해주는 워크플로 오류 수정 (#12)
  .github/workflows/auto-project.yml
Labels: 🐞 BugFix

#22 [Feature] SQLite3 데이터베이스에 초기 데이터 추가
  package-lock.json
  package.json
  server/data/attendance.json
  server/data/departments.json
  server/data/members.json
  server/data/users.json
  server/data/vacationRequests.json
  server/database.js
  server/index.js
  server/passwords.js
  src/fetchData.js
Labels: ✨ Feature, 📬 API

#24 [Feature] Header, Navgation, Layout 컴포넌트 추가
  index.html
  public/favicon.ico
  public/icons/clock-icon.svg
  public/icons/home-icon.svg
  public/icons/members-icon.svg
  public/icons/profile-icon.svg
  public/images/logo.svg
  public/images/user-default.svg
  public/vite.svg
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Main/Main.css
  src/components/Main/Main.js
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.js
  src/counter.js
  src/index.css
  src/index.js
  src/javascript.svg
  src/layouts/Layout/Layout.js
  src/main.js
  src/pages/Home/Home.css
  src/pages/Home/Home.js
  src/pages/PageNotFound/PageNotFound.css
  src/pages/PageNotFound/PageNotFound.js
  src/reset.css
  src/style.css
Labels: ✨ Feature

#25 [Settings] 초기 프로젝트 구성 파일 업데이트
  .eslintrc.cjs
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc.js
  .stylelintrc.cjs
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/icons/clock-icon.svg
  public/icons/home-icon.svg
  public/icons/members-icon.svg
  public/icons/profile-icon.svg
  public/images/logo.svg
  public/images/user-default.svg
  public/vite.svg
  server/data/attendance.json
  server/data/departments.json
  server/data/members.json
  server/data/users.json
  server/data/vacationRequests.json
  server/database.js
  server/index.js
  server/passwords.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Main/Main.css
  src/components/Main/Main.js
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.js
  src/counter.js
  src/fetchData.js
  src/index.css
  src/index.js
  src/javascript.svg
  src/layouts/Layout/Layout.js
  src/main.js
  src/pages/Home/Home.css
  src/pages/Home/Home.js
  src/pages/PageNotFound/PageNotFound.css
  src/pages/PageNotFound/PageNotFound.js
  src/reset.css
  src/style.css
  vite.config.js
Labels: ⚙ Setting

#30 [Refactor] 자잘한 오류 및 디자인 수정
  index.html
  src/components/Layout.js
  src/components/NavBar/NavBar.css
  src/index.css
  src/routes/Route.js
Labels: 🎨 Html&css, 🔨 Refactor

#33 [Bug/Refactor] svg 색상 변경 버그 해결 및 리팩토링
  public/icons/clock-icon.svg
  public/icons/home-icon.svg
  public/icons/members-icon.svg
  public/icons/profile-icon.svg
  src/App.js
  src/components/Icon/Icon.js
  src/components/NavBar/Menu.js
  src/components/NavBar/NavBar.js
  src/routes/Route.js
  src/utils/constants.js
  src/utils/icons.js
Labels: 🐞 BugFix, 🔨 Refactor

#35 데이터베이스 테스트 코드 추가
  server/checkData.js
  server/database.js
Labels: Testing

#52 아바타 컴포넌트 추가
  src/components/Avatar/Avatar.css
  src/components/Avatar/Avatar.js
Labels: ✨ Feature

#54 Title 컴포넌트 추가
  src/components/Title/Title.css
  src/components/Title/Title.js
  src/index.css
  src/pages/Home/Home.js
  src/pages/Members/Members.js
  src/pages/Profile/Profile.js
  src/pages/WorkManage/WorkManage.js
Labels: ✨ Feature

#56 [Feat] PersonalInfo 컴포넌트 추가
  src/components/Avatar/Avatar.css
  src/components/Avatar/Avatar.js
  src/components/Button/Button.css
  src/components/Button/Button.js
  src/components/Icon/Icon.js
  src/components/PersonalInfo/PersonalInfo.css
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/ProfileInfo.css
  src/components/PersonalInfo/ProfileInfo.js
  src/components/PersonalInfo/WorkInfo.css
  src/components/PersonalInfo/WorkInfo.js
  src/components/ProgressRing.js/ProgressRing.css
  src/components/ProgressRing.js/ProgressRing.js
  src/pages/Profile/Profile.js
Labels: ✨ Feature

#55 input 컴포넌트 추가
  src/components/Input/Input.css
  src/components/Input/Input.js
Labels: ✨ Feature

#58 [Design] Button 컴포넌트 hover 스타일 수정
  src/components/Button/Button.css
  src/index.css
Labels: 🎨 Html&css

#59 [Feat] 공지사항 데이터베이스 추가 및 직원정보 근무유형, 부서명 추가
  public/images/announcements_01.png
  public/images/announcements_02.png
  public/images/announcements_03.png
  public/images/announcements_04.png
  public/images/announcements_05.png
  server/checkData.js
  server/data/announcements.json
  server/data/members.json
  server/database.js
  server/index.js
  src/fetchData.js
Labels: ✨ Feature

#61 [Feat] 모달 컴포넌트 제작
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
Labels: ✨ Feature

#62 [Feat] 프로필 페이지 퍼블리싱
  src/components/PersonalInfo/PersonalDetail.js
  src/components/PersonalInfo/PersonalDetails.css
  src/components/PersonalInfo/PersonalDetails.js
  src/components/PersonalInfo/PersonalInfo.js
  src/components/PersonalInfo/ProfileInfo.js
  src/pages/Profile/Profile.js
Labels: ✨ Feature

#64 [Feat] Table 컴포넌트 추가
  src/components/Table/Table.css
  src/components/Table/Table.js
Labels: ✨ Feature

#67 [Feat] 로그인 페이지 퍼블리싱
  public/images/dashboard.png
  src/components/Input/Input.css
  src/components/SignInForm/SignInForm.js
  src/index.css
  src/pages/SignIn/SignIn.css
  src/pages/SignIn/SignIn.js
  src/pages/index.js
  src/routes/Route.js
  src/utils/constants.js
Labels: 🎨 Html&css

#72 [Design] 구성원 페이지 디자인 수정
  src/components/Input/Input.css
  src/components/Pagination/Pagination.css
  src/components/Pagination/Pagination.js
  src/pages/Members/Members.css
  src/pages/Members/Members.js
Labels: 🎨 Html&css
